In [1]:
# screener_endpoint = 'https://financialmodelingprep.com/stable/company-screener?
# PB ratio
# Debt to equity
# Revenue Growth
# Gross Profit margin
# Altman z score

In [1]:
from datetime import datetime
from dotenv import load_dotenv
import pandas as pd
import requests
import os
import yfinance as yf

In [2]:
load_dotenv()

True

In [4]:
api_key = os.getenv("API_KEY")

In [5]:
symbols_string = "AAPL, TSLA, AMZN, MSFT, NVDA, GOOGL, META, NFLX, JPM, V, BAC, PYPL, DIS, T, PFE, COST, INTC, KO, TGT, NKE, SPY, BA, BABA, XOM, WMT, GE, CSCO, VZ, JNJ, CVX, PLTR, SQ, SHOP, SBUX, SOFI, HOOD, RBLX, SNAP, AMD, UBER, FDX, ABBV, ETSY, MRNA, LMT, GM, F, LCID, CCL, DAL, UAL, AAL, TSM, SONY, ET, MRO, COIN, RIVN, RIOT, CPRX, VWO, SPYG, NOK, ROKU, VIAC, ATVI, BIDU, DOCU, ZM, PINS, TLRY, WBA, MGM, NIO, C, GS, WFC, ADBE, PEP, UNH, CARR, HCA, TWTR, BILI, SIRI, FUBO, RKT"
symbols_split = symbols_string.split(',')
symbols = [s.strip() for s in symbols_split]

In [6]:
ticker = 'AAPL'
income_endpoint = f"https://financialmodelingprep.com/stable/income-statement?symbol={ticker}&apikey={api_key}"
income_data = requests.get(income_endpoint)
income = income_data.json()
income

[{'date': '2025-09-27',
  'symbol': 'AAPL',
  'reportedCurrency': 'USD',
  'cik': '0000320193',
  'filingDate': '2025-10-31',
  'acceptedDate': '2025-10-31 06:01:26',
  'fiscalYear': '2025',
  'period': 'FY',
  'revenue': 416161000000,
  'costOfRevenue': 220960000000,
  'grossProfit': 195201000000,
  'researchAndDevelopmentExpenses': 34550000000,
  'generalAndAdministrativeExpenses': 27601000000,
  'sellingAndMarketingExpenses': 0,
  'sellingGeneralAndAdministrativeExpenses': 27601000000,
  'otherExpenses': 0,
  'operatingExpenses': 62151000000,
  'costAndExpenses': 283111000000,
  'netInterestIncome': 0,
  'interestIncome': 0,
  'interestExpense': 0,
  'depreciationAndAmortization': 11698000000,
  'ebitda': 144427000000,
  'ebit': 132729000000,
  'nonOperatingIncomeExcludingInterest': 321000000,
  'operatingIncome': 133050000000,
  'totalOtherIncomeExpensesNet': -321000000,
  'incomeBeforeTax': 132729000000,
  'incomeTaxExpense': 20719000000,
  'netIncomeFromContinuingOperations': 112010000000,
  'netIncomeFromDiscontinuedOperations': 0,
  'otherAdjustmentsToNetIncome': 0,
  'netIncome': 112010000000,
  'netIncomeDeductions': 0,
  'bottomLineNetIncome': 112010000000,
  'eps': 7.49,
  'epsDiluted': 7.46,
  'weightedAverageShsOut': 14948500000,
  'weightedAverageShsOutDil': 15004697000},
 {'date': '2024-09-28',
  'symbol': 'AAPL',
  'reportedCurrency': 'USD',
  'cik': '0000320193',
  'filingDate': '2024-11-01',
  'acceptedDate': '2024-11-01 06:01:36',
  'fiscalYear': '2024',
  'period': 'FY',
  'revenue': 391035000000,
  'costOfRevenue': 210352000000,
  'grossProfit': 180683000000,
  'researchAndDevelopmentExpenses': 31370000000,
  'generalAndAdministrativeExpenses': 7458000000,
  'sellingAndMarketingExpenses': 18639000000,
  'sellingGeneralAndAdministrativeExpenses': 26097000000,
  'otherExpenses': 0,
  'operatingExpenses': 57467000000,
  'costAndExpenses': 267819000000,
  'netInterestIncome': 0,
  'interestIncome': 0,
  'interestExpense': 0,
  'depreciationAndAmortization': 11445000000,
  'ebitda': 134930000000,
  'ebit': 123485000000,
  'nonOperatingIncomeExcludingInterest': -269000000,
  'operatingIncome': 123216000000,
  'totalOtherIncomeExpensesNet': 269000000,
  'incomeBeforeTax': 123485000000,
  'incomeTaxExpense': 29749000000,
  'netIncomeFromContinuingOperations': 93736000000,
  'netIncomeFromDiscontinuedOperations': 0,
  'otherAdjustmentsToNetIncome': 0,
  'netIncome': 93736000000,
  'netIncomeDeductions': 0,
  'bottomLineNetIncome': 93736000000,
  'eps': 6.11,
  'epsDiluted': 6.08,
  'weightedAverageShsOut': 15343783000,
  'weightedAverageShsOutDil': 15408095000},
 {'date': '2023-09-30',
  'symbol': 'AAPL',
  'reportedCurrency': 'USD',
  'cik': '0000320193',
  'filingDate': '2023-11-03',
  'acceptedDate': '2023-11-02 18:08:27',
  'fiscalYear': '2023',
  'period': 'FY',
  'revenue': 383285000000,
  'costOfRevenue': 214137000000,
  'grossProfit': 169148000000,
  'researchAndDevelopmentExpenses': 29915000000,
  'generalAndAdministrativeExpenses': 0,
  'sellingAndMarketingExpenses': 0,
  'sellingGeneralAndAdministrativeExpenses': 24932000000,
  'otherExpenses': 0,
  'operatingExpenses': 54847000000,
  'costAndExpenses': 268984000000,
  'netInterestIncome': -183000000,
  'interestIncome': 3750000000,
  'interestExpense': 3933000000,
  'depreciationAndAmortization': 11519000000,
  'ebitda': 129188000000,
  'ebit': 117669000000,
  'nonOperatingIncomeExcludingInterest': -3368000000,
  'operatingIncome': 114301000000,
  'totalOtherIncomeExpensesNet': -565000000,
  'incomeBeforeTax': 113736000000,
  'incomeTaxExpense': 16741000000,
  'netIncomeFromContinuingOperations': 96995000000,
  'netIncomeFromDiscontinuedOperations': 0,
  'otherAdjustmentsToNetIncome': 0,
  'netIncome': 96995000000,
  'netIncomeDeductions': 0,
  'bottomLineNetIncome': 96995000000,
  'eps': 6.16,
  'epsDiluted': 6.13,
  'weightedAverageShsOut': 15744231000,
  'weightedAverageShsOutDil': 15812547000},
 {'date': '2022-09-24',
  'symbol': 'AAPL',
  'reportedCurrency': 'USD',
  'cik': '0000320193',
  'filingDate': '2022-10-28',
  'acceptedDate': '2022-10-27 18:01:14',
  'fiscalYear': '2022',
  'period': 'FY',
  'revenue': 394328000000,
  'costOfRevenue': 223546000000,
  'grossProfit': 170782000000,
  'researchAndDevelopmentExpenses': 26251000000,
  'generalAndAdministrativeExpenses': 0,
  'sellingAndMarketingExpenses': 0,
  'sellingGeneralAndAdministrativeExpenses': 25094000000,
  'otherExpenses': 0,
  'operatingExpenses': 51345000000,
  'costAndExpenses': 274891000000,
  'netInterestIncome': -106000000,
  'interestIncome': 2825000000,
  'interestExpense': 2931000000,
  'depreciationAndAmortization': 11104000000,
  'ebitda': 133138000000,
  'ebit': 122034000000,
  'nonOperatingIncomeExcludingInterest': -2597000000,
  'operatingIncome': 119437000000,
  'totalOtherIncomeExpensesNet': -334000000,
  'incomeBeforeTax': 119103000000,
  'incomeTaxExpense': 19300000000,
  'netIncomeFromContinuingOperations': 99803000000,
  'netIncomeFromDiscontinuedOperations': 0,
  'otherAdjustmentsToNetIncome': 0,
  'netIncome': 99803000000,
  'netIncomeDeductions': 0,
  'bottomLineNetIncome': 99803000000,
  'eps': 6.15,
  'epsDiluted': 6.11,
  'weightedAverageShsOut': 16215963000,
  'weightedAverageShsOutDil': 16325819000},
 {'date': '2021-09-25',
  'symbol': 'AAPL',
  'reportedCurrency': 'USD',
  'cik': '0000320193',
  'filingDate': '2021-10-29',
  'acceptedDate': '2021-10-28 18:04:28',
  'fiscalYear': '2021',
  'period': 'FY',
  'revenue': 365817000000,
  'costOfRevenue': 212981000000,
  'grossProfit': 152836000000,
  'researchAndDevelopmentExpenses': 21914000000,
  'generalAndAdministrativeExpenses': 0,
  'sellingAndMarketingExpenses': 0,
  'sellingGeneralAndAdministrativeExpenses': 21973000000,
  'otherExpenses': 0,
  'operatingExpenses': 43887000000,
  'costAndExpenses': 256868000000,
  'netInterestIncome': 198000000,
  'interestIncome': 2843000000,
  'interestExpense': 2645000000,
  'depreciationAndAmortization': 11284000000,
  'ebitda': 123136000000,
  'ebit': 111852000000,
  'nonOperatingIncomeExcludingInterest': -2903000000,
  'operatingIncome': 108949000000,
  'totalOtherIncomeExpensesNet': 258000000,
  'incomeBeforeTax': 109207000000,
  'incomeTaxExpense': 14527000000,
  'netIncomeFromContinuingOperations': 94680000000,
  'netIncomeFromDiscontinuedOperations': 0,
  'otherAdjustmentsToNetIncome': 0,
  'netIncome': 94680000000,
  'netIncomeDeductions': 0,
  'bottomLineNetIncome': 94680000000,
  'eps': 5.67,
  'epsDiluted': 5.61,
  'weightedAverageShsOut': 16701272000,
  'weightedAverageShsOutDil': 16864919000}]

In [7]:
balance_endpoint = f"https://financialmodelingprep.com/stable/balance-sheet-statement?symbol={ticker}&apikey={api_key}"
balance_data = requests.get(balance_endpoint)
balance = balance_data.json()
balance

[{'date': '2025-09-27',
  'symbol': 'AAPL',
  'reportedCurrency': 'USD',
  'cik': '0000320193',
  'filingDate': '2025-10-31',
  'acceptedDate': '2025-10-31 06:01:26',
  'fiscalYear': '2025',
  'period': 'FY',
  'cashAndCashEquivalents': 35934000000,
  'shortTermInvestments': 18763000000,
  'cashAndShortTermInvestments': 54697000000,
  'netReceivables': 72957000000,
  'accountsReceivables': 39777000000,
  'otherReceivables': 33180000000,
  'inventory': 5718000000,
  'prepaids': 0,
  'otherCurrentAssets': 14585000000,
  'totalCurrentAssets': 147957000000,
  'propertyPlantEquipmentNet': 49834000000,
  'goodwill': 0,
  'intangibleAssets': 0,
  'goodwillAndIntangibleAssets': 0,
  'longTermInvestments': 77723000000,
  'taxAssets': 20777000000,
  'otherNonCurrentAssets': 62950000000,
  'totalNonCurrentAssets': 211284000000,
  'otherAssets': 0,
  'totalAssets': 359241000000,
  'totalPayables': 82876000000,
  'accountPayables': 69860000000,
  'otherPayables': 13016000000,
  'accruedExpenses': 8919000000,
  'shortTermDebt': 20329000000,
  'capitalLeaseObligationsCurrent': 2117000000,
  'taxPayables': 0,
  'deferredRevenue': 9055000000,
  'otherCurrentLiabilities': 42335000000,
  'totalCurrentLiabilities': 165631000000,
  'longTermDebt': 78328000000,
  'capitalLeaseObligationsNonCurrent': 11603000000,
  'deferredRevenueNonCurrent': 0,
  'deferredTaxLiabilitiesNonCurrent': 0,
  'otherNonCurrentLiabilities': 29946000000,
  'totalNonCurrentLiabilities': 119877000000,
  'otherLiabilities': 0,
  'capitalLeaseObligations': 13720000000,
  'totalLiabilities': 285508000000,
  'treasuryStock': 0,
  'preferredStock': 0,
  'commonStock': 93568000000,
  'retainedEarnings': -14264000000,
  'additionalPaidInCapital': 0,
  'accumulatedOtherComprehensiveIncomeLoss': -5571000000,
  'otherTotalStockholdersEquity': 0,
  'totalStockholdersEquity': 73733000000,
  'totalEquity': 73733000000,
  'minorityInterest': 0,
  'totalLiabilitiesAndTotalEquity': 359241000000,
  'totalInvestments': 96486000000,
  'totalDebt': 112377000000,
  'netDebt': 76443000000},
 {'date': '2024-09-28',
  'symbol': 'AAPL',
  'reportedCurrency': 'USD',
  'cik': '0000320193',
  'filingDate': '2024-11-01',
  'acceptedDate': '2024-11-01 06:01:36',
  'fiscalYear': '2024',
  'period': 'FY',
  'cashAndCashEquivalents': 29943000000,
  'shortTermInvestments': 35228000000,
  'cashAndShortTermInvestments': 65171000000,
  'netReceivables': 66243000000,
  'accountsReceivables': 33410000000,
  'otherReceivables': 32833000000,
  'inventory': 7286000000,
  'prepaids': 0,
  'otherCurrentAssets': 14287000000,
  'totalCurrentAssets': 152987000000,
  'propertyPlantEquipmentNet': 45680000000,
  'goodwill': 0,
  'intangibleAssets': 0,
  'goodwillAndIntangibleAssets': 0,
  'longTermInvestments': 91479000000,
  'taxAssets': 19499000000,
  'otherNonCurrentAssets': 55335000000,
  'totalNonCurrentAssets': 211993000000,
  'otherAssets': 0,
  'totalAssets': 364980000000,
  'totalPayables': 95561000000,
  'accountPayables': 68960000000,
  'otherPayables': 26601000000,
  'accruedExpenses': 0,
  'shortTermDebt': 20879000000,
  'capitalLeaseObligationsCurrent': 1632000000,
  'taxPayables': 26601000000,
  'deferredRevenue': 8249000000,
  'otherCurrentLiabilities': 50071000000,
  'totalCurrentLiabilities': 176392000000,
  'longTermDebt': 85750000000,
  'capitalLeaseObligationsNonCurrent': 10798000000,
  'deferredRevenueNonCurrent': 0,
  'deferredTaxLiabilitiesNonCurrent': 0,
  'otherNonCurrentLiabilities': 35090000000,
  'totalNonCurrentLiabilities': 131638000000,
  'otherLiabilities': 0,
  'capitalLeaseObligations': 12430000000,
  'totalLiabilities': 308030000000,
  'treasuryStock': 0,
  'preferredStock': 0,
  'commonStock': 83276000000,
  'retainedEarnings': -19154000000,
  'additionalPaidInCapital': 0,
  'accumulatedOtherComprehensiveIncomeLoss': -7172000000,
  'otherTotalStockholdersEquity': 0,
  'totalStockholdersEquity': 56950000000,
  'totalEquity': 56950000000,
  'minorityInterest': 0,
  'totalLiabilitiesAndTotalEquity': 364980000000,
  'totalInvestments': 126707000000,
  'totalDebt': 119059000000,
  'netDebt': 89116000000},
 {'date': '2023-09-30',
  'symbol': 'AAPL',
  'reportedCurrency': 'USD',
  'cik': '0000320193',
  'filingDate': '2023-11-03',
  'acceptedDate': '2023-11-02 18:08:27',
  'fiscalYear': '2023',
  'period': 'FY',
  'cashAndCashEquivalents': 29965000000,
  'shortTermInvestments': 31590000000,
  'cashAndShortTermInvestments': 61555000000,
  'netReceivables': 60985000000,
  'accountsReceivables': 29508000000,
  'otherReceivables': 31477000000,
  'inventory': 6331000000,
  'prepaids': 0,
  'otherCurrentAssets': 14695000000,
  'totalCurrentAssets': 143566000000,
  'propertyPlantEquipmentNet': 54376000000,
  'goodwill': 0,
  'intangibleAssets': 0,
  'goodwillAndIntangibleAssets': 0,
  'longTermInvestments': 100544000000,
  'taxAssets': 17852000000,
  'otherNonCurrentAssets': 36245000000,
  'totalNonCurrentAssets': 209017000000,
  'otherAssets': 0,
  'totalAssets': 352583000000,
  'totalPayables': 71430000000,
  'accountPayables': 62611000000,
  'otherPayables': 8819000000,
  'accruedExpenses': 0,
  'shortTermDebt': 15807000000,
  'capitalLeaseObligationsCurrent': 1575000000,
  'taxPayables': 8819000000,
  'deferredRevenue': 8061000000,
  'otherCurrentLiabilities': 48435000000,
  'totalCurrentLiabilities': 145308000000,
  'longTermDebt': 95281000000,
  'capitalLeaseObligationsNonCurrent': 11267000000,
  'deferredRevenueNonCurrent': 0,
  'deferredTaxLiabilitiesNonCurrent': 0,
  'otherNonCurrentLiabilities': 38581000000,
  'totalNonCurrentLiabilities': 145129000000,
  'otherLiabilities': 0,
  'capitalLeaseObligations': 12842000000,
  'totalLiabilities': 290437000000,
  'treasuryStock': 0,
  'preferredStock': 0,
  'commonStock': 73812000000,
  'retainedEarnings': -214000000,
  'additionalPaidInCapital': 0,
  'accumulatedOtherComprehensiveIncomeLoss': -11452000000,
  'otherTotalStockholdersEquity': 0,
  'totalStockholdersEquity': 62146000000,
  'totalEquity': 62146000000,
  'minorityInterest': 0,
  'totalLiabilitiesAndTotalEquity': 352583000000,
  'totalInvestments': 132134000000,
  'totalDebt': 123930000000,
  'netDebt': 93965000000},
 {'date': '2022-09-24',
  'symbol': 'AAPL',
  'reportedCurrency': 'USD',
  'cik': '0000320193',
  'filingDate': '2022-10-28',
  'acceptedDate': '2022-10-27 18:01:14',
  'fiscalYear': '2022',
  'period': 'FY',
  'cashAndCashEquivalents': 23646000000,
  'shortTermInvestments': 24658000000,
  'cashAndShortTermInvestments': 48304000000,
  'netReceivables': 60932000000,
  'accountsReceivables': 28184000000,
  'otherReceivables': 32748000000,
  'inventory': 4946000000,
  'prepaids': 0,
  'otherCurrentAssets': 21223000000,
  'totalCurrentAssets': 135405000000,
  'propertyPlantEquipmentNet': 52534000000,
  'goodwill': 0,
  'intangibleAssets': 0,
  'goodwillAndIntangibleAssets': 0,
  'longTermInvestments': 120805000000,
  'taxAssets': 15375000000,
  'otherNonCurrentAssets': 28636000000,
  'totalNonCurrentAssets': 217350000000,
  'otherAssets': 0,
  'totalAssets': 352755000000,
  'totalPayables': 70667000000,
  'accountPayables': 64115000000,
  'otherPayables': 6552000000,
  'accruedExpenses': 0,
  'shortTermDebt': 21110000000,
  'capitalLeaseObligationsCurrent': 1663000000,
  'taxPayables': 6552000000,
  'deferredRevenue': 7912000000,
  'otherCurrentLiabilities': 52630000000,
  'totalCurrentLiabilities': 153982000000,
  'longTermDebt': 98959000000,
  'capitalLeaseObligationsNonCurrent': 10748000000,
  'deferredRevenueNonCurrent': 0,
  'deferredTaxLiabilitiesNonCurrent': 0,
  'otherNonCurrentLiabilities': 38394000000,
  'totalNonCurrentLiabilities': 148101000000,
  'otherLiabilities': 0,
  'capitalLeaseObligations': 12411000000,
  'totalLiabilities': 302083000000,
  'treasuryStock': 0,
  'preferredStock': 0,
  'commonStock': 64849000000,
  'retainedEarnings': -3068000000,
  'additionalPaidInCapital': 0,
  'accumulatedOtherComprehensiveIncomeLoss': -11109000000,
  'otherTotalStockholdersEquity': 0,
  'totalStockholdersEquity': 50672000000,
  'totalEquity': 50672000000,
  'minorityInterest': 0,
  'totalLiabilitiesAndTotalEquity': 352755000000,
  'totalInvestments': 145463000000,
  'totalDebt': 132480000000,
  'netDebt': 108834000000},
 {'date': '2021-09-25',
  'symbol': 'AAPL',
  'reportedCurrency': 'USD',
  'cik': '0000320193',
  'filingDate': '2021-10-29',
  'acceptedDate': '2021-10-28 18:04:28',
  'fiscalYear': '2021',
  'period': 'FY',
  'cashAndCashEquivalents': 34940000000,
  'shortTermInvestments': 27699000000,
  'cashAndShortTermInvestments': 62639000000,
  'netReceivables': 51506000000,
  'accountsReceivables': 26278000000,
  'otherReceivables': 25228000000,
  'inventory': 6580000000,
  'prepaids': 0,
  'otherCurrentAssets': 14111000000,
  'totalCurrentAssets': 134836000000,
  'propertyPlantEquipmentNet': 49527000000,
  'goodwill': 0,
  'intangibleAssets': 0,
  'goodwillAndIntangibleAssets': 0,
  'longTermInvestments': 127877000000,
  'taxAssets': 0,
  'otherNonCurrentAssets': 38762000000,
  'totalNonCurrentAssets': 216166000000,
  'otherAssets': 0,
  'totalAssets': 351002000000,
  'totalPayables': 54763000000,
  'accountPayables': 54763000000,
  'otherPayables': 0,
  'accruedExpenses': 0,
  'shortTermDebt': 15613000000,
  'capitalLeaseObligationsCurrent': 1528000000,
  'taxPayables': 0,
  'deferredRevenue': 7612000000,
  'otherCurrentLiabilities': 45965000000,
  'totalCurrentLiabilities': 125481000000,
  'longTermDebt': 109106000000,
  'capitalLeaseObligationsNonCurrent': 10275000000,
  'deferredRevenueNonCurrent': 0,
  'deferredTaxLiabilitiesNonCurrent': 0,
  'otherNonCurrentLiabilities': 43050000000,
  'totalNonCurrentLiabilities': 162431000000,
  'otherLiabilities': 0,
  'capitalLeaseObligations': 11803000000,
  'totalLiabilities': 287912000000,
  'treasuryStock': 0,
  'preferredStock': 0,
  'commonStock': 57365000000,
  'retainedEarnings': 5562000000,
  'additionalPaidInCapital': 0,
  'accumulatedOtherComprehensiveIncomeLoss': 163000000,
  'otherTotalStockholdersEquity': 0,
  'totalStockholdersEquity': 63090000000,
  'totalEquity': 63090000000,
  'minorityInterest': 0,
  'totalLiabilitiesAndTotalEquity': 351002000000,
  'totalInvestments': 155576000000,
  'totalDebt': 136522000000,
  'netDebt': 101582000000}]

In [8]:
cash_endpoint = f"https://financialmodelingprep.com/stable/cash-flow-statement?symbol={ticker}&apikey={api_key}"
cash_data = requests.get(cash_endpoint)
cash = cash_data.json()
cash

[{'date': '2025-09-27',
  'symbol': 'AAPL',
  'reportedCurrency': 'USD',
  'cik': '0000320193',
  'filingDate': '2025-10-31',
  'acceptedDate': '2025-10-31 06:01:26',
  'fiscalYear': '2025',
  'period': 'FY',
  'netIncome': 112010000000,
  'depreciationAndAmortization': 11698000000,
  'deferredIncomeTax': 0,
  'stockBasedCompensation': 12863000000,
  'changeInWorkingCapital': -25000000000,
  'accountsReceivables': -7029000000,
  'inventory': 1400000000,
  'accountsPayables': 902000000,
  'otherWorkingCapital': -20273000000,
  'otherNonCashItems': -89000000,
  'netCashProvidedByOperatingActivities': 111482000000,
  'investmentsInPropertyPlantAndEquipment': -12715000000,
  'acquisitionsNet': 0,
  'purchasesOfInvestments': -24407000000,
  'salesMaturitiesOfInvestments': 53797000000,
  'otherInvestingActivities': -1480000000,
  'netCashProvidedByInvestingActivities': 15195000000,
  'netDebtIssuance': -8483000000,
  'longTermNetDebtIssuance': -6451000000,
  'shortTermNetDebtIssuance': -2032000000,
  'netStockIssuance': -90711000000,
  'netCommonStockIssuance': -90711000000,
  'commonStockIssuance': 0,
  'commonStockRepurchased': -90711000000,
  'netPreferredStockIssuance': 0,
  'netDividendsPaid': -15421000000,
  'commonDividendsPaid': -15421000000,
  'preferredDividendsPaid': 0,
  'otherFinancingActivities': -6071000000,
  'netCashProvidedByFinancingActivities': -120686000000,
  'effectOfForexChangesOnCash': 0,
  'netChangeInCash': 5991000000,
  'cashAtEndOfPeriod': 35934000000,
  'cashAtBeginningOfPeriod': 29943000000,
  'operatingCashFlow': 111482000000,
  'capitalExpenditure': -12715000000,
  'freeCashFlow': 98767000000,
  'incomeTaxesPaid': 43369000000,
  'interestPaid': 0},
 {'date': '2024-09-28',
  'symbol': 'AAPL',
  'reportedCurrency': 'USD',
  'cik': '0000320193',
  'filingDate': '2024-11-01',
  'acceptedDate': '2024-11-01 06:01:36',
  'fiscalYear': '2024',
  'period': 'FY',
  'netIncome': 93736000000,
  'depreciationAndAmortization': 11445000000,
  'deferredIncomeTax': 0,
  'stockBasedCompensation': 11688000000,
  'changeInWorkingCapital': 3651000000,
  'accountsReceivables': -5144000000,
  'inventory': -1046000000,
  'accountsPayables': 6020000000,
  'otherWorkingCapital': 3821000000,
  'otherNonCashItems': -2266000000,
  'netCashProvidedByOperatingActivities': 118254000000,
  'investmentsInPropertyPlantAndEquipment': -9447000000,
  'acquisitionsNet': 0,
  'purchasesOfInvestments': -48656000000,
  'salesMaturitiesOfInvestments': 62346000000,
  'otherInvestingActivities': -1308000000,
  'netCashProvidedByInvestingActivities': 2935000000,
  'netDebtIssuance': -5998000000,
  'longTermNetDebtIssuance': -9958000000,
  'shortTermNetDebtIssuance': 3960000000,
  'netStockIssuance': -94949000000,
  'netCommonStockIssuance': -94949000000,
  'commonStockIssuance': 0,
  'commonStockRepurchased': -94949000000,
  'netPreferredStockIssuance': 0,
  'netDividendsPaid': -15234000000,
  'commonDividendsPaid': -15234000000,
  'preferredDividendsPaid': 0,
  'otherFinancingActivities': -5802000000,
  'netCashProvidedByFinancingActivities': -121983000000,
  'effectOfForexChangesOnCash': 0,
  'netChangeInCash': -794000000,
  'cashAtEndOfPeriod': 29943000000,
  'cashAtBeginningOfPeriod': 30737000000,
  'operatingCashFlow': 118254000000,
  'capitalExpenditure': -9447000000,
  'freeCashFlow': 108807000000,
  'incomeTaxesPaid': 26102000000,
  'interestPaid': 0},
 {'date': '2023-09-30',
  'symbol': 'AAPL',
  'reportedCurrency': 'USD',
  'cik': '0000320193',
  'filingDate': '2023-11-03',
  'acceptedDate': '2023-11-02 18:08:27',
  'fiscalYear': '2023',
  'period': 'FY',
  'netIncome': 96995000000,
  'depreciationAndAmortization': 11519000000,
  'deferredIncomeTax': 0,
  'stockBasedCompensation': 10833000000,
  'changeInWorkingCapital': -6577000000,
  'accountsReceivables': -417000000,
  'inventory': -1618000000,
  'accountsPayables': -1889000000,
  'otherWorkingCapital': -2653000000,
  'otherNonCashItems': -2227000000,
  'netCashProvidedByOperatingActivities': 110543000000,
  'investmentsInPropertyPlantAndEquipment': -10959000000,
  'acquisitionsNet': 0,
  'purchasesOfInvestments': -29513000000,
  'salesMaturitiesOfInvestments': 45514000000,
  'otherInvestingActivities': -1337000000,
  'netCashProvidedByInvestingActivities': 3705000000,
  'netDebtIssuance': -9901000000,
  'longTermNetDebtIssuance': -5923000000,
  'shortTermNetDebtIssuance': -3978000000,
  'netStockIssuance': -77550000000,
  'netCommonStockIssuance': -77550000000,
  'commonStockIssuance': 0,
  'commonStockRepurchased': -77550000000,
  'netPreferredStockIssuance': 0,
  'netDividendsPaid': -15025000000,
  'commonDividendsPaid': -15025000000,
  'preferredDividendsPaid': 0,
  'otherFinancingActivities': -6012000000,
  'netCashProvidedByFinancingActivities': -108488000000,
  'effectOfForexChangesOnCash': 0,
  'netChangeInCash': 5760000000,
  'cashAtEndOfPeriod': 30737000000,
  'cashAtBeginningOfPeriod': 24977000000,
  'operatingCashFlow': 110543000000,
  'capitalExpenditure': -10959000000,
  'freeCashFlow': 99584000000,
  'incomeTaxesPaid': 18679000000,
  'interestPaid': 3803000000},
 {'date': '2022-09-24',
  'symbol': 'AAPL',
  'reportedCurrency': 'USD',
  'cik': '0000320193',
  'filingDate': '2022-10-28',
  'acceptedDate': '2022-10-27 18:01:14',
  'fiscalYear': '2022',
  'period': 'FY',
  'netIncome': 99803000000,
  'depreciationAndAmortization': 11104000000,
  'deferredIncomeTax': 895000000,
  'stockBasedCompensation': 9038000000,
  'changeInWorkingCapital': 1200000000,
  'accountsReceivables': -9343000000,
  'inventory': 1484000000,
  'accountsPayables': 9448000000,
  'otherWorkingCapital': -389000000,
  'otherNonCashItems': 111000000,
  'netCashProvidedByOperatingActivities': 122151000000,
  'investmentsInPropertyPlantAndEquipment': -10708000000,
  'acquisitionsNet': -306000000,
  'purchasesOfInvestments': -76923000000,
  'salesMaturitiesOfInvestments': 67363000000,
  'otherInvestingActivities': -1780000000,
  'netCashProvidedByInvestingActivities': -22354000000,
  'netDebtIssuance': -123000000,
  'longTermNetDebtIssuance': -4078000000,
  'shortTermNetDebtIssuance': 3955000000,
  'netStockIssuance': -89402000000,
  'netCommonStockIssuance': -89402000000,
  'commonStockIssuance': 0,
  'commonStockRepurchased': -89402000000,
  'netPreferredStockIssuance': 0,
  'netDividendsPaid': -14841000000,
  'commonDividendsPaid': -14841000000,
  'preferredDividendsPaid': 0,
  'otherFinancingActivities': -6383000000,
  'netCashProvidedByFinancingActivities': -110749000000,
  'effectOfForexChangesOnCash': 0,
  'netChangeInCash': -10952000000,
  'cashAtEndOfPeriod': 24977000000,
  'cashAtBeginningOfPeriod': 35929000000,
  'operatingCashFlow': 122151000000,
  'capitalExpenditure': -10708000000,
  'freeCashFlow': 111443000000,
  'incomeTaxesPaid': 19573000000,
  'interestPaid': 2865000000},
 {'date': '2021-09-25',
  'symbol': 'AAPL',
  'reportedCurrency': 'USD',
  'cik': '0000320193',
  'filingDate': '2021-10-29',
  'acceptedDate': '2021-10-28 18:04:28',
  'fiscalYear': '2021',
  'period': 'FY',
  'netIncome': 94680000000,
  'depreciationAndAmortization': 11284000000,
  'deferredIncomeTax': -4774000000,
  'stockBasedCompensation': 7906000000,
  'changeInWorkingCapital': -4911000000,
  'accountsReceivables': -14028000000,
  'inventory': -2642000000,
  'accountsPayables': 12326000000,
  'otherWorkingCapital': -567000000,
  'otherNonCashItems': -147000000,
  'netCashProvidedByOperatingActivities': 104038000000,
  'investmentsInPropertyPlantAndEquipment': -11085000000,
  'acquisitionsNet': -33000000,
  'purchasesOfInvestments': -109558000000,
  'salesMaturitiesOfInvestments': 106483000000,
  'otherInvestingActivities': -352000000,
  'netCashProvidedByInvestingActivities': -14545000000,
  'netDebtIssuance': 12665000000,
  'longTermNetDebtIssuance': 11643000000,
  'shortTermNetDebtIssuance': 1022000000,
  'netStockIssuance': -84866000000,
  'netCommonStockIssuance': -84866000000,
  'commonStockIssuance': 1105000000,
  'commonStockRepurchased': -85971000000,
  'netPreferredStockIssuance': 0,
  'netDividendsPaid': -14467000000,
  'commonDividendsPaid': -14467000000,
  'preferredDividendsPaid': 0,
  'otherFinancingActivities': -6685000000,
  'netCashProvidedByFinancingActivities': -93353000000,
  'effectOfForexChangesOnCash': 0,
  'netChangeInCash': -3860000000,
  'cashAtEndOfPeriod': 35929000000,
  'cashAtBeginningOfPeriod': 39789000000,
  'operatingCashFlow': 104038000000,
  'capitalExpenditure': -11085000000,
  'freeCashFlow': 92953000000,
  'incomeTaxesPaid': 25385000000,
  'interestPaid': 2687000000}]

In [9]:
income_growth_endpoint = f"https://financialmodelingprep.com/stable/income-statement-growth?symbol={ticker}&apikey={api_key}"
income_growth_data = requests.get(income_growth_endpoint)
income_growth = income_growth_data.json()
income_growth

[{'symbol': 'AAPL',
  'date': '2025-09-27',
  'fiscalYear': '2025',
  'period': 'FY',
  'reportedCurrency': 'USD',
  'growthRevenue': 0.0642551178283274,
  'growthCostOfRevenue': 0.050429755837833726,
  'growthGrossProfit': 0.08035066940442653,
  'growthGrossProfitRatio': 0.015123771791588903,
  'growthResearchAndDevelopmentExpenses': 0.10137073637233025,
  'growthGeneralAndAdministrativeExpenses': 2.700858138911236,
  'growthSellingAndMarketingExpenses': -1,
  'growthOtherExpenses': 0,
  'growthOperatingExpenses': 0.08150764786747176,
  'growthCostAndExpenses': 0.057098264126144896,
  'growthInterestIncome': 0,
  'growthInterestExpense': 0,
  'growthDepreciationAndAmortization': 0.022105723023154215,
  'growthEBITDA': 0.07038464388942414,
  'growthOperatingIncome': 0.07981106349824699,
  'growthIncomeBeforeTax': 0.0748592946511722,
  'growthIncomeTaxExpense': -0.3035396147769673,
  'growthNetIncome': 0.19495177946573355,
  'growthEPS': 0.22585924713584285,
  'growthEPSDiluted': 0.2269736842105263,
  'growthWeightedAverageShsOut': -0.025761769441082424,
  'growthWeightedAverageShsOutDil': -0.02618091334457634,
  'growthEBIT': 0.0748592946511722,
  'growthNonOperatingIncomeExcludingInterest': 2.193308550185874,
  'growthNetInterestIncome': 0,
  'growthTotalOtherIncomeExpensesNet': -2.193308550185874,
  'growthNetIncomeFromContinuingOperations': 0.19495177946573355,
  'growthOtherAdjustmentsToNetIncome': 0,
  'growthNetIncomeDeductions': 0},
 {'symbol': 'AAPL',
  'date': '2024-09-28',
  'fiscalYear': '2024',
  'period': 'FY',
  'reportedCurrency': 'USD',
  'growthRevenue': 0.020219940775141214,
  'growthCostOfRevenue': -0.017675600199872046,
  'growthGrossProfit': 0.06819471705252206,
  'growthGrossProfitRatio': 0.04702395474011335,
  'growthResearchAndDevelopmentExpenses': 0.04863780712017383,
  'growthGeneralAndAdministrativeExpenses': 0,
  'growthSellingAndMarketingExpenses': 0,
  'growthOtherExpenses': 0,
  'growthOperatingExpenses': 0.04776924900176856,
  'growthCostAndExpenses': -0.004331112631234571,
  'growthInterestIncome': -1,
  'growthInterestExpense': -1,
  'growthDepreciationAndAmortization': -0.006424168764649709,
  'growthEBITDA': 0.044446852648852835,
  'growthOperatingIncome': 0.07799581805933456,
  'growthIncomeBeforeTax': 0.08571604417246959,
  'growthIncomeTaxExpense': 0.7770145152619318,
  'growthNetIncome': -0.033599670086086914,
  'growthEPS': -0.008116883116883088,
  'growthEPSDiluted': -0.008156606851549727,
  'growthWeightedAverageShsOut': -0.02543458616683152,
  'growthWeightedAverageShsOutDil': -0.02557791606880283,
  'growthEBIT': 0.04942678190517469,
  'growthNonOperatingIncomeExcludingInterest': 0.9201306413301663,
  'growthNetInterestIncome': 1,
  'growthTotalOtherIncomeExpensesNet': 1.4761061946902654,
  'growthNetIncomeFromContinuingOperations': -0.033599670086086914,
  'growthOtherAdjustmentsToNetIncome': 0,
  'growthNetIncomeDeductions': 0},
 {'symbol': 'AAPL',
  'date': '2023-09-30',
  'fiscalYear': '2023',
  'period': 'FY',
  'reportedCurrency': 'USD',
  'growthRevenue': -0.028004605303199367,
  'growthCostOfRevenue': -0.04208977123276641,
  'growthGrossProfit': -0.00956775304188966,
  'growthGrossProfitRatio': 0.01896804496777955,
  'growthResearchAndDevelopmentExpenses': 0.13957563521389663,
  'growthGeneralAndAdministrativeExpenses': 0,
  'growthSellingAndMarketingExpenses': 0,
  'growthOtherExpenses': 0,
  'growthOperatingExpenses': 0.06820527802122894,
  'growthCostAndExpenses': -0.02148851726684395,
  'growthInterestIncome': 0.3274336283185841,
  'growthInterestExpense': 0.34186284544524054,
  'growthDepreciationAndAmortization': 0.03737391930835735,
  'growthEBITDA': -0.029668464300199794,
  'growthOperatingIncome': -0.04300174987650393,
  'growthIncomeBeforeTax': -0.04506183723331906,
  'growthIncomeTaxExpense': -0.13259067357512955,
  'growthNetIncome': -0.028135426790777834,
  'growthEPS': 0.001626016260162567,
  'growthEPSDiluted': 0.0032733224222585224,
  'growthWeightedAverageShsOut': -0.029090594249629207,
  'growthWeightedAverageShsOutDil': -0.031439280320331865,
  'growthEBIT': -0.035768720192733174,
  'growthNonOperatingIncomeExcludingInterest': -0.29688101655756644,
  'growthNetInterestIncome': -0.7264150943396226,
  'growthTotalOtherIncomeExpensesNet': -0.6916167664670658,
  'growthNetIncomeFromContinuingOperations': -0.028135426790777834,
  'growthOtherAdjustmentsToNetIncome': 0,
  'growthNetIncomeDeductions': 0},
 {'symbol': 'AAPL',
  'date': '2022-09-24',
  'fiscalYear': '2022',
  'period': 'FY',
  'reportedCurrency': 'USD',
  'growthRevenue': 0.07793787604184606,
  'growthCostOfRevenue': 0.04960536385874796,
  'growthGrossProfit': 0.11741997958596143,
  'growthGrossProfitRatio': 0.03662743860969033,
  'growthResearchAndDevelopmentExpenses': 0.19791001186456147,
  'growthGeneralAndAdministrativeExpenses': 0,
  'growthSellingAndMarketingExpenses': 0,
  'growthOtherExpenses': 0,
  'growthOperatingExpenses': 0.16993642764372138,
  'growthCostAndExpenses': 0.07016444243736082,
  'growthInterestIncome': -0.006331340133661625,
  'growthInterestExpense': 0.10812854442344046,
  'growthDepreciationAndAmortization': -0.015951790145338533,
  'growthEBITDA': 0.08122726091476092,
  'growthOperatingIncome': 0.09626522501353844,
  'growthIncomeBeforeTax': 0.0906169018469512,
  'growthIncomeTaxExpense': 0.32856061127555586,
  'growthNetIncome': 0.05410857625686523,
  'growthEPS': 0.08465608465608473,
  'growthEPSDiluted': 0.08912655971479501,
  'growthWeightedAverageShsOut': -0.029058205865996313,
  'growthWeightedAverageShsOutDil': -0.03196576277656596,
  'growthEBIT': 0.09103100525694668,
  'growthNonOperatingIncomeExcludingInterest': 0.10540819841543231,
  'growthNetInterestIncome': -1.5353535353535352,
  'growthTotalOtherIncomeExpensesNet': -2.294573643410853,
  'growthNetIncomeFromContinuingOperations': 0.05410857625686523,
  'growthOtherAdjustmentsToNetIncome': 0,
  'growthNetIncomeDeductions': 0},
 {'symbol': 'AAPL',
  'date': '2021-09-25',
  'fiscalYear': '2021',
  'period': 'FY',
  'reportedCurrency': 'USD',
  'growthRevenue': 0.33259384733074693,
  'growthCostOfRevenue': 0.25608785142634716,
  'growthGrossProfit': 0.4561911658218682,
  'growthGrossProfitRatio': 0.09274942911055713,
  'growthResearchAndDevelopmentExpenses': 0.16862201365187712,
  'growthGeneralAndAdministrativeExpenses': 0,
  'growthSellingAndMarketingExpenses': 0,
  'growthOtherExpenses': 0,
  'growthOperatingExpenses': 0.13496948381090307,
  'growthCostAndExpenses': 0.23359602741239127,
  'growthInterestIncome': -0.2444857826202498,
  'growthInterestExpense': -0.07935955447267665,
  'growthDepreciationAndAmortization': 0.020622286541244574,
  'growthEBITDA': 0.519822266107134,
  'growthOperatingIncome': 0.6435704803282646,
  'growthIncomeBeforeTax': 0.6277444068503972,
  'growthIncomeTaxExpense': 0.5007231404958677,
  'growthNetIncome': 0.649161310550243,
  'growthEPS': 0.7129909365558912,
  'growthEPSDiluted': 0.7103658536585368,
  'growthWeightedAverageShsOut': -0.037508214414619906,
  'growthWeightedAverageShsOutDil': -0.037841562180835994,
  'growthEBIT': 0.5987079069235607,
  'growthNonOperatingIncomeExcludingInterest': 0.2102829162132753,
  'growthNetInterestIncome': -0.7775280898876404,
  'growthTotalOtherIncomeExpensesNet': -0.6787048567870486,
  'growthNetIncomeFromContinuingOperations': 0.649161310550243,
  'growthOtherAdjustmentsToNetIncome': 0,
  'growthNetIncomeDeductions': 0}]

In [25]:
aapl_ticker = yf.Ticker('AAPL')
shares = aapl_ticker.get_shares_full(start='2021-10-01')
df_shares = pd.DataFrame(data=shares,  index=None, )
df_shares.reset_index(inplace=True)
df_shares = df_shares.rename(columns={'index': 'Date', 0: 'Shares'})
df_shares['Date'] = pd.to_datetime(df_shares['Date']).dt.date
df_shares.head()
print(type(df_shares['Date'][0]))

<class 'datetime.date'>

In [26]:
price_history = aapl_ticker.history('5y')
price_history = price_history.reset_index()
price_history.head()

,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits
0,2021-05-27 00:00:00-04:00,123.247652,124.417351,121.921988,122.116936,94625600,0.0,0.0
1,2021-05-28 00:00:00-04:00,122.399590,122.623786,121.405346,121.463829,71311100,0.0,0.0
2,2021-06-01 00:00:00-04:00,121.921986,122.185166,120.810769,121.142181,67637100,0.0,0.0
3,2021-06-02 00:00:00-04:00,121.142168,122.077929,120.917979,121.902473,59278900,0.0,0.0
4,2021-06-03 00:00:00-04:00,121.532062,121.697768,120.021193,120.420845,76229200,0.0,0.0

### Apple's P/B Ratio

In [12]:
pb_ratios = []
market_caps = []
for year in balance:
    # Step 1: Find filing date
    file_date = year['filingDate']
    # Step 2: Find price on filing date
    filing_date_stock_price = price_history[price_history['Date'] == file_date]
    # Step 3: Convert to datetime
    file_date = pd.to_datetime(file_date)
    # Step 4: Find closest date available for share data
    df_shares['Date'] = pd.to_datetime(df_shares['Date'])
    closest_date = (df_shares['Date'] - file_date).abs().idxmin()
    closest_row = df_shares.loc[closest_date]
    # Step 5: Find market cap
    market_cap = filing_date_stock_price['Close'].iloc[0] * closest_row['Shares']
    market_cap = float(market_cap)
    market_caps.append(market_cap)
    # Step 6: Find P/B ratio
    shareholder_equity = year['totalStockholdersEquity']
    ratio = market_cap / shareholder_equity
    pb_ratio = float(ratio)
    pb_ratios.append(pb_ratio)

print(pb_ratios)
print(market_caps)

[54.26439409983269, 60.01295476946444, 43.88498195309785, 47.997828461564076, 38.0284664694967]
[4001076570162.964, 3417737774121.0, 2727276088457.2188, 2432145963804.375, 2399215949560.547]

In [13]:
market_cap_endpoint = f"https://financialmodelingprep.com/stable/market-capitalization?symbol=AAPL&apikey={api_key}"
market_cap_data = requests.get(market_cap_endpoint)
market_cap = market_cap_data.json()
market_cap

[{'symbol': 'AAPL', 'date': '2026-05-27', 'marketCap': 4598097106140}]

### Apple's D/E Ratio

In [14]:
de_ratios = []

for year in balance:
    # Step 1: Pull shareholder and total debt from balance sheet
    shareholder_equity = year['totalStockholdersEquity']
    total_debt = year['totalDebt']
    # Step 2: Divide numbers
    de_ratio = total_debt / shareholder_equity
    # Step 3: Append yearly ratios to list
    de_ratios.append(de_ratio)

print(de_ratios)

[1.5241072518411023, 2.090588235294118, 1.9941750072410132, 2.6144616356173036, 2.163924552226977]

### Apple revenue growth

In [15]:
revenue_growth = []
for year in income_growth:
    growth = year['growthRevenue']
    revenue_growth.append(growth)

revenue_growth

[0.0642551178283274,
 0.020219940775141214,
 -0.028004605303199367,
 0.07793787604184606,
 0.33259384733074693]

### Apple Gross Profit Margin

In [16]:
gross_profit_margin = []

for year in income:
    total_revenue = year['revenue']
    gross_profit = year['grossProfit']
    gpm = gross_profit / total_revenue
    gross_profit_margin.append(gpm)

gross_profit_margin

[0.4690516410716045,
 0.4620634981523393,
 0.4413112957720756,
 0.43309630561360085,
 0.4177935962516778]

### Altman Z-score for manufacturing firms

In [17]:
# Altman Z-Score = 1.2A + 1.4B + 3.3C + 0.6D + 1.0E

# Where:

# A = working capital (current assets - current liabilities) / total assets
# B = retained earnings / total assets
# C = earnings before interest and tax / total assets
# D = market value of equity / total liabilities
# E = sales / total assets

### Altman Z-score for nonmanufacturing

In [18]:
# Altman Z-Score = 6.56A + 3.26B + 6.72C + 1.05D

# Where:

# A = working capital (current assets − current liabilities) / total assets
# B = retained earnings / total assets
# C = earnings before interest and taxes / total assets
# D = book value of equity / total liabilities

altman_z_score = []

for x in range(0, 5):
    # Find total assets and total liabilities
    total_assets = balance[x]['totalAssets']
    total_liabilities = balance[x]['totalLiabilities']
    # Find current assets and current liabilities
    current_assets = balance[x]['totalCurrentAssets']
    current_liabilities = balance[x]['totalCurrentLiabilities']
    # Calculate working capital and A
    working_capital = current_assets - current_liabilities
    A = working_capital / total_assets
    A *= 6.56 
    print(A)
    # Calculate B
    retained_earnings = balance[x]['retainedEarnings']
    B = (retained_earnings / total_assets)
    B *= 3.26
    print(B)
    # Calculate C
    ebit = income[x]['ebit']
    C = ebit / total_assets
    C *= 6.72
    print(C)
    # Calculate D
    D = balance[x]['totalStockholdersEquity'] / total_liabilities
    D *= 1.05
    print(D)

    score = A + B + C + D
    altman_z_score.append(score)

print(altman_z_score)

-0.3227399990535601
-0.12944134995727102
2.4828426599413764
0.27116455580929427
-0.4206718176338429
-0.17108345662776042
2.2736018411967778
0.19412881862156284
-0.03241086495945635
-0.001978654671382341
2.242693720343862
0.22467282061169894
-0.345466740372213
-0.028353049566979913
2.3247536675596376
0.17612907710794715
0.1748388898068957
0.051658167189930534
2.1414277981322045
0.23008592903387146
[2.3018258667398395, 1.8759753855567374, 2.432977021324722, 2.127062954728392, 2.598010784162902]

In [19]:
income_endpoint = f"https://financialmodelingprep.com/stable/income-statement?symbol=SQ&apikey={api_key}"
income_data = requests.get(income_endpoint)
income = income_data.json()
income

[{'date': '2025-12-31',
  'symbol': 'SQ',
  'reportedCurrency': 'USD',
  'cik': '0001512673',
  'filingDate': '2026-02-26',
  'acceptedDate': '2026-02-26 16:07:56',
  'fiscalYear': '2025',
  'period': 'FY',
  'revenue': 24193683000,
  'costOfRevenue': 13833754000,
  'grossProfit': 10359929000,
  'researchAndDevelopmentExpenses': 0,
  'generalAndAdministrativeExpenses': 1997587000,
  'sellingAndMarketingExpenses': 2273072000,
  'sellingGeneralAndAdministrativeExpenses': 4270659000,
  'otherExpenses': 4380864000,
  'operatingExpenses': 8651523000,
  'costAndExpenses': 22485277000,
  'netInterestIncome': -1244000,
  'interestIncome': 0,
  'interestExpense': 1244000,
  'depreciationAndAmortization': 0,
  'ebitda': 1691155000,
  'ebit': 1691155000,
  'nonOperatingIncomeExcludingInterest': 17251000,
  'operatingIncome': 1708406000,
  'totalOtherIncomeExpensesNet': -18495000,
  'incomeBeforeTax': 1689911000,
  'incomeTaxExpense': 385701000,
  'netIncomeFromContinuingOperations': -1426000,
  'netIncomeFromDiscontinuedOperations': 0,
  'otherAdjustmentsToNetIncome': 0,
  'netIncome': -1426000,
  'netIncomeDeductions': 0,
  'bottomLineNetIncome': -1426000,
  'eps': 2.13,
  'epsDiluted': 2.1,
  'weightedAverageShsOut': 612243000,
  'weightedAverageShsOutDil': 622838000},
 {'date': '2024-12-31',
  'symbol': 'SQ',
  'reportedCurrency': 'USD',
  'cik': '0001512673',
  'filingDate': '2025-02-24',
  'acceptedDate': '2025-02-24 21:17:17',
  'fiscalYear': '2024',
  'period': 'FY',
  'revenue': 24121053000,
  'costOfRevenue': 15232017000,
  'grossProfit': 8889036000,
  'researchAndDevelopmentExpenses': 2914415000,
  'generalAndAdministrativeExpenses': 2149099000,
  'sellingAndMarketingExpenses': 1984265000,
  'sellingGeneralAndAdministrativeExpenses': 4133364000,
  'otherExpenses': 948930000,
  'operatingExpenses': 7996709000,
  'costAndExpenses': 23228726000,
  'netInterestIncome': -9302000,
  'interestIncome': 0,
  'interestExpense': 9302000,
  'depreciationAndAmortization': 307763000,
  'ebitda': 1345598000,
  'ebit': 1037835000,
  'nonOperatingIncomeExcludingInterest': -145508000,
  'operatingIncome': 892327000,
  'totalOtherIncomeExpensesNet': 464827000,
  'incomeBeforeTax': 1357154000,
  'incomeTaxExpense': -1509343000,
  'netIncomeFromContinuingOperations': 2866497000,
  'netIncomeFromDiscontinuedOperations': 0,
  'otherAdjustmentsToNetIncome': 0,
  'netIncome': 2897047000,
  'netIncomeDeductions': 0,
  'bottomLineNetIncome': 2897047000,
  'eps': 4.7,
  'epsDiluted': 4.55,
  'weightedAverageShsOut': 616993000,
  'weightedAverageShsOutDil': 636390000},
 {'date': '2023-12-31',
  'symbol': 'SQ',
  'reportedCurrency': 'USD',
  'cik': '0001512673',
  'filingDate': '2024-02-22',
  'acceptedDate': '2024-02-22 16:18:13',
  'fiscalYear': '2023',
  'period': 'FY',
  'revenue': 21915623000,
  'costOfRevenue': 14410737000,
  'grossProfit': 7504886000,
  'researchAndDevelopmentExpenses': 2720819000,
  'generalAndAdministrativeExpenses': 2209190000,
  'sellingAndMarketingExpenses': 2019009000,
  'sellingGeneralAndAdministrativeExpenses': 4228199000,
  'otherExpenses': 834707000,
  'operatingExpenses': 7783725000,
  'costAndExpenses': 22194462000,
  'netInterestIncome': 47221000,
  'interestIncome': 47221000,
  'interestExpense': 0,
  'depreciationAndAmortization': 419673000,
  'ebitda': 390530000,
  'ebit': -29143000,
  'nonOperatingIncomeExcludingInterest': -249696000,
  'operatingIncome': -278839000,
  'totalOtherIncomeExpensesNet': 249696000,
  'incomeBeforeTax': -29143000,
  'incomeTaxExpense': -8019000,
  'netIncomeFromContinuingOperations': -21124000,
  'netIncomeFromDiscontinuedOperations': 0,
  'otherAdjustmentsToNetIncome': 0,
  'netIncome': 9772000,
  'netIncomeDeductions': 0,
  'bottomLineNetIncome': 9772000,
  'eps': 0.016,
  'epsDiluted': 0.0159,
  'weightedAverageShsOut': 608856000,
  'weightedAverageShsOutDil': 614024000},
 {'date': '2022-12-31',
  'symbol': 'SQ',
  'reportedCurrency': 'USD',
  'cik': '0001512673',
  'filingDate': '2023-02-23',
  'acceptedDate': '2023-02-23 16:23:08',
  'fiscalYear': '2022',
  'period': 'FY',
  'revenue': 17531587000,
  'costOfRevenue': 11539695000,
  'grossProfit': 5991892000,
  'researchAndDevelopmentExpenses': 2135612000,
  'generalAndAdministrativeExpenses': 1686849000,
  'sellingAndMarketingExpenses': 2057951000,
  'sellingGeneralAndAdministrativeExpenses': 3744800000,
  'otherExpenses': 689441000,
  'operatingExpenses': 6569853000,
  'costAndExpenses': 18109548000,
  'netInterestIncome': -36228000,
  'interestIncome': 0,
  'interestExpense': 36228000,
  'depreciationAndAmortization': 470334000,
  'ebitda': -58755000,
  'ebit': -529089000,
  'nonOperatingIncomeExcludingInterest': -95443000,
  'operatingIncome': -624532000,
  'totalOtherIncomeExpensesNet': 59215000,
  'incomeBeforeTax': -565317000,
  'incomeTaxExpense': -12312000,
  'netIncomeFromContinuingOperations': -553005000,
  'netIncomeFromDiscontinuedOperations': 0,
  'otherAdjustmentsToNetIncome': 0,
  'netIncome': -540747000,
  'netIncomeDeductions': 0,
  'bottomLineNetIncome': -540747000,
  'eps': -0.93,
  'epsDiluted': -0.93,
  'weightedAverageShsOut': 578949000,
  'weightedAverageShsOutDil': 578949000},
 {'date': '2021-12-31',
  'symbol': 'SQ',
  'reportedCurrency': 'USD',
  'cik': '0001512673',
  'filingDate': '2022-02-24',
  'acceptedDate': '2022-02-24 16:19:13',
  'fiscalYear': '2021',
  'period': 'FY',
  'revenue': 17661203000,
  'costOfRevenue': 13241380000,
  'grossProfit': 4419823000,
  'researchAndDevelopmentExpenses': 1399079000,
  'generalAndAdministrativeExpenses': 983326000,
  'sellingAndMarketingExpenses': 1617189000,
  'sellingGeneralAndAdministrativeExpenses': 2600515000,
  'otherExpenses': 187991000,
  'operatingExpenses': 4187585000,
  'costAndExpenses': 17428965000,
  'netInterestIncome': -33124000,
  'interestIncome': 0,
  'interestExpense': 33124000,
  'depreciationAndAmortization': 217893000,
  'ebitda': 408479000,
  'ebit': 190586000,
  'nonOperatingIncomeExcludingInterest': -29474000,
  'operatingIncome': 161112000,
  'totalOtherIncomeExpensesNet': -3650000,
  'incomeBeforeTax': 157462000,
  'incomeTaxExpense': -1364000,
  'netIncomeFromContinuingOperations': 158826000,
  'netIncomeFromDiscontinuedOperations': 0,
  'otherAdjustmentsToNetIncome': 0,
  'netIncome': 166284000,
  'netIncomeDeductions': 0,
  'bottomLineNetIncome': 166284000,
  'eps': 0.36,
  'epsDiluted': 0.33,
  'weightedAverageShsOut': 458432000,
  'weightedAverageShsOutDil': 501779000}]

In [6]:
yf_ticker = yf.Ticker('SQ')
yf_ticker.history(repair=True)

$SQ: possibly delisted; no price data found  (period=1mo) (Yahoo error = "No data found, symbol may be delisted")

Empty DataFrame
Columns: [Open, High, Low, Close, Adj Close, Volume]
Index: []